### ISSUE TITLE
Jessie and gcc 4.7

### ISSUE THREAD

**Issue by ShabbyX** [zultron/rtai-deb#5]
Hi John,

I just upgraded from Wheezy to Jessie (because Wheezy's Automake was stuck at 1.11 and I needed new features) and long story short, I can't install the RTAI debian packages because they depend on gcc 4.7

Is it that Jessie upgraded gcc after you made the packages? If not, was there a specific reason for it?

**Comment by zultron** [comment]
I'm working on packages for Jessie, and did finally [address this problem](https://github.com/zultron/dxsbuild/blob/linux-3.16.7/scripts/package/linux.sh#L34-L37).  The 3.16 packages will be built with gcc-4.8.

**Comment by ShabbyX** [comment]
Thanks!
